name       : budgie-trash-applet
version    : 1.1.0
release    : 2
source     :
    - https://github.com/EbonJaeger/budgie-trash-applet/archive/v1.1.0.tar.gz : 6d4af0b5530f0332523f8c282c39c6524b05b5f426ffd229d4cfe7fb25714197
license    : Apache-2.0
component  : desktop.budgie
summary    : Manage items in your trash bin right from the Budgie panel.
description: |
    Allows the managing of the user trash bin from the Budgie panel.
    Gives you the option to view, restore, and permanently delete items in the trash bin.
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(glib-2.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
