name       : budgie-trash-applet
version    : 1.2.0
release    : 5
source     :
    - https://github.com/EbonJaeger/budgie-trash-applet/archive/v1.2.0.tar.gz : 34e5fbb825c8fd90bdc381154e7791419101d4556bd79821f96badcede4d8f31
license    : Apache-2.0
component  : desktop.budgie
summary    : Manage items in your trash bin right from the Budgie panel.
description: |
    Allows the managing of the user trash bin from the Budgie panel.
    Gives you the option to view, restore, and permanently delete items in the trash bin.
builddeps  :
    - pkgconfig(budgie-1.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
