name       : budgie-trash-applet
version    : 2.1.1
release    : 10
source     :
    - https://github.com/EbonJaeger/budgie-trash-applet/archive/refs/tags/v2.1.1-1.tar.gz : 129e4aa0b8d74a4284f9731012c3292f440ff7671fddc130dc0a91139d6225e3
license    : Apache-2.0
component  : desktop.budgie
homepage   : https://github.com/EbonJaeger/budgie-trash-applet
summary    : Manage items in your trash bin right from the Budgie panel.
description: |
    Allows the managing of the user trash bin from the Budgie panel.
    Gives you the option to view, restore, and permanently delete items in the trash bin.
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(libnotify)
    - sassc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
