name       : budgie-trash-applet
version    : 2.1.0
release    : 8
source     :
    - https://github.com/EbonJaeger/budgie-trash-applet/archive/refs/tags/v2.1.0.tar.gz : 41c6c63412da8a6b7de90118d43e6a37fe9ae41b9c520f5e7747cd6726191b1c
license    : Apache-2.0
component  : desktop.budgie
homepage   : https://github.com/EbonJaeger/budgie-trash-applet
summary    : Manage items in your trash bin right from the Budgie panel.
description: |
    Allows the managing of the user trash bin from the Budgie panel.
    Gives you the option to view, restore, and permanently delete items in the trash bin.
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(libnotify)
    - sassc
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
